
name: RobinJob

inputs:
  num_minutes:
    required: true
    default: 355
  input_file_name:
    required: true
  input_artifact_name:
    required: true
    default: ""
  job_number:
    required: true

runs-on: ubuntu-24.04

runs:
    steps:
      # Define stop time.
      - name: SetStopTime
        run: |
          JOB_STOP_TIME=`date --date="+${{ inputs.num_minutes }} mins" +%s`
          echo "JOB_STOP_TIME=$JOB_STOP_TIME" >> $GITHUB_ENV

      # Set up environment
      - name: Setup
        run: . ./scripts/Setup.sh

      # Download artifact from last job.
      - name: Download last output
        if: inputs.input_artifact_name != ""
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.input_artifact_name }}

      # Run code
      - name: Run
        run: ./Search 55 $JOB_STOP_TIME "${{ inputs.input_file_name }}" "job${{ inputs.job_number }}.txt"

      # Save plot of deltas.
      - name: Save delta plot
        uses: actions/upload-artifact@v4
        with:
          name: delta_plots_${{ inputs.job_number }}
          path: |
            DeltaPlot.png
            DeltaPlotScaled.png
            
      # Save output file 
      - name: Save job output
        uses: actions/upload-artifact@v4
        with:
          name: out${{ inputs.job_number }}
          path: |
            job${{ inputs.job_number }}.txt


