# Long run for occasional checks.

name: Long run

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  MY_DEPENDENCY_FLAGS: "-Lprimesieve -Wl,-rpath=primesieve -Iprimesieve/include -Lmpfr/src/.libs -Wl,-rpath=mpfr/src/.libs -Impfr/src -Lgmp-6.2.1/.libs  -Wl,-rpath=gmp-6.2.1/.libs"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Set up environment
      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install libmpfr-dev gnuplot llvm-12 clang-12
          # perf list

      # build libprimesieve 7.9.
      # Ubuntu 20.04 only has version 7.5.
      - name: SetupPrimeSieve
        run: |
          git clone --depth 1 --branch v7.9 https://github.com/kimwalisch/primesieve
          cd primesieve
          sed -i 's/private/public/g' include/primesieve/iterator.hpp
          CC="clang-12 -fuse-ld=gold -march=native" CXX="clang++-12 -fuse-ld=gold -march=native" cmake -DBUILD_TESTS=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=TRUE -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON .
          make -j
          ctest
          echo "Run ls"
          ls
          echo "Run ls CMakeFiles"
          ls CMakeFiles

      # Compile test segments to assembly
      #- name: CompileAsmTest
      #  run: |
      #    llc-12 -O3 -o - CheckAssembly/LLVM_WideInt.ll

      # Run tests.
      - name: RunTests
        run: |
          clang++-12 -std=c++20 -fuse-ld=gold -g -Wall -O3 -flto=thin -march=native -lmpfr test/TestBigFloat.cpp -o TestBigFloat
          ./TestBigFloat

      # Compile code
      - name: Compile
        run: |
          clang++-12 --version
          /usr/bin/ld -v
          lscpu
          clang++-12 -std=c++20 -fuse-ld=gold -g -Wall -O3 -flto=thin -march=native -Wl,-plugin-opt=whole-program-visibility -Lprimesieve -Wl,-rpath=primesieve -Iprimesieve/include Search.cpp -lmpfr -lprimesieve -o Search
          #clang++ -std=c++20 -DNDEBUG -Wall -O3 -flto -march=native -lmpfr -lprimesieve Search.cpp -o Search_ndebug

      # Run code straight, no profiling.
      # Skip this - experience shows that the overhead from
      # running perf record (at low frequency) is small.
      #- name: Run
      #  run: ./Search

      # Run code straight, no profiling, ndebug version.
      # Skip this - experience shows that the overhead from
      # running perf record (at low frequency) is small.
      #- name: Run (ndebug)
      #  run: ./Search_ndebug

      # Run code (perf)
      - name: Run (perf)
        run: sudo perf record --call-graph dwarf -F 10 -o perf.data ./Search 49

      # Print perf report.
      - name: Report from perf
        run: sudo perf report -i perf.data --call-graph=graph,0.1

      # Print perf source annotations.
      - name: Source annotations from perf
        run: sudo perf annotate -i perf.data

      # Run code
      # - name: Run
      #   run: ./Search

      # Save plot of deltas.
      - name: Save delta plot
        uses: actions/upload-artifact@v2
        with:
          name: delta_plots
          path: |
            DeltaPlot.png
            DeltaPlotScaled.png
