# Print basic system info. 
name: PrintSystemInfo

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: '0'
      - name: Setup
        run: |
          apt-get update
          apt-get install hwloc
      - name: PrintSystemInfo
        run: |
          git rev-parse --short HEAD
          echo
          . ./scripts/PrintSystemInfo.sh
