# Long run, extending across multiple jobs.

name: Run_2jobs_quick

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  MY_DEPENDENCY_FLAGS: "-Lprimesieve -Wl,-rpath=primesieve -Iprimesieve/include -Lmpfr/src/.libs -Wl,-rpath=mpfr/src/.libs -Impfr/src -Lgmp-6.3.0/.libs  -Wl,-rpath=gmp-6.3.0/.libs"
  MY_LLVM_VER: 18

jobs:
  job1:
    runs-on: ubuntu-24.04
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: run job
      uses: ./.github/workflows/JobAction
      with:
        num_minutes: 10
        #input_file_name: ''
        input_file_name: checkpoints/Checkpoint_84hrs_20231223.txt
        input_artifact_name: ''
        job_number: 1

  job2:
    runs-on: ubuntu-24.04
    needs: job1
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: run job
      uses: ./.github/workflows/JobAction
      with:
        num_minutes: 10
        input_file_name: job1.txt
        input_artifact_name: out1
        job_number: 2


  
