# Long run, extending across multiple jobs.

name: Run_Njobs

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  MY_DEPENDENCY_FLAGS: "-Lprimesieve -Wl,-rpath=primesieve -Iprimesieve/include -Lmpfr/src/.libs -Wl,-rpath=mpfr/src/.libs -Impfr/src -Lgmp-6.3.0/.libs  -Wl,-rpath=gmp-6.3.0/.libs"


jobs:

  job1:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Define stop time.
      - name: SetStopTime
        run: |
          JOB_STOP_TIME=`date --date="+6 hours -10 mins" +%s`
          echo "JOB_STOP_TIME=$JOB_STOP_TIME" >> $GITHUB_ENV
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Set up environment
      - name: Setup
        run: . ./scripts/Setup.sh

      # Run code (perf)
      - name: Run (perf)
        run: sudo perf record --call-graph dwarf -F 10 -o perf.data ./Search 55 $JOB_STOP_TIME "" "job1.bin"

      # Print perf report.
      - name: Report from perf
        run: sudo PATH=`pwd`:$PATH perf report -i perf.data --call-graph=graph,0.1

      # Print perf source annotations.
      - name: Source annotations from perf
        run: sudo PATH=`pwd`:$PATH perf annotate -i perf.data


      # Save plot of deltas.
      - name: Save delta plot
        uses: actions/upload-artifact@v3
        with:
          name: delta_plots_1
          path: |
            DeltaPlot.png
            DeltaPlotScaled.png
            
      # Save output file 
      - name: Save job1 output
        uses: actions/upload-artifact@v3
        with:
          name: out1
          path: |
            job1.bin


  job2:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    needs: job1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Define stop time.
      - name: SetStopTime
        run: |
          JOB_STOP_TIME=`date --date="+6 hours -10 mins" +%s`
          echo "JOB_STOP_TIME=$JOB_STOP_TIME" >> $GITHUB_ENV
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Set up environment
      - name: Setup
        run: . ./scripts/Setup.sh

      # Download artifact from last job.
      - name: Download last output
        uses: actions/download-artifact@v3
        with:
          name: out1

      # Run code (perf)
      - name: Run (perf)
        run: sudo perf record --call-graph dwarf -F 10 -o perf.data ./Search 55 $JOB_STOP_TIME "job1.bin" "job2.bin"

      # Print perf report.
      - name: Report from perf
        run: sudo PATH=`pwd`:$PATH perf report -i perf.data --call-graph=graph,0.1

      # Print perf source annotations.
      - name: Source annotations from perf
        run: sudo PATH=`pwd`:$PATH perf annotate -i perf.data


      # Save plot of deltas.
      - name: Save delta plot
        uses: actions/upload-artifact@v3
        with:
          name: delta_plots_2
          path: |
            DeltaPlot.png
            DeltaPlotScaled.png
            
      # Save output file 
      - name: Save job2 output
        uses: actions/upload-artifact@v3
        with:
          name: out2
          path: |
            job2.bin
