name: RunSearch
on: [push]
jobs:
  do_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: sudo apt-get update
      - run: sudo apt-get install libmpfr-dev
