# This is a basic workflow to help you get started with Actions

name: TimePrimeGen

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  MY_DEPENDENCY_FLAGS: "-Lprimesieve -Wl,-rpath=primesieve -Iprimesieve/include"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Set up environment
      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install clang-12

      # build libprimesieve
      - name: SetupPrimeSieve
        run: bash scripts/SetupPrimeSieve_main.sh

      # Build programs for summing primes.
      - name: BuildSumPrimes
        run: |
          clang++-12 -std=c++20 -Wall -O3 -march=native $MY_DEPENDENCY_FLAGS test/TimerPrimeGen1.cpp -lprimesieve -o TimerPrimeGen1
          clang++-12 -std=c++20 -Wall -O3 -march=native $MY_DEPENDENCY_FLAGS test/TimerPrimeGen2.cpp -lprimesieve -o TimerPrimeGen2
          clang++-12 -std=c++20 -Wall -O3 -march=native $MY_DEPENDENCY_FLAGS test/TimerPrimeGen3.cpp -lprimesieve -o TimerPrimeGen3
          clang++-12 -std=c++20 -Wall -O3 -march=native $MY_DEPENDENCY_FLAGS test/TimerPrimeGen4.cpp -lprimesieve -o TimerPrimeGen4

      # Time the summing of primes.
      - name: RunTimerSumPrimes1
        run: |
          ./TimerPrimeGen1

      # Time the summing of primes.
      - name: RunTimerSumPrimes2
        run: |
          ./TimerPrimeGen2

      # Time the summing of primes.
      - name: RunTimerSumPrimes3
        run: |
          ./TimerPrimeGen3

      # Time the summing of primes.
      - name: RunTimerSumPrimes4
        run: |
          ./TimerPrimeGen4

      # build libprimesieve
      - name: SetupPrimeSieve_tmp
        run: |
          rm -rf primesieve
          bash scripts/SetupPrimeSieve_tmp.sh

      # Build programs for summing primes.
      - name: BuildSumPrimes
        run: |
          clang++-12 -std=c++20 -Wall -O3 -march=native $MY_DEPENDENCY_FLAGS test/TimerPrimeGen1.cpp -lprimesieve -o TimerPrimeGen1
          clang++-12 -std=c++20 -Wall -O3 -march=native $MY_DEPENDENCY_FLAGS test/TimerPrimeGen2.cpp -lprimesieve -o TimerPrimeGen2
          clang++-12 -std=c++20 -Wall -O3 -march=native $MY_DEPENDENCY_FLAGS test/TimerPrimeGen3.cpp -lprimesieve -o TimerPrimeGen3
          clang++-12 -std=c++20 -Wall -O3 -march=native $MY_DEPENDENCY_FLAGS test/TimerPrimeGen4.cpp -lprimesieve -o TimerPrimeGen4

      # Time the summing of primes.
      - name: RunTimerSumPrimes1
        run: |
          ./TimerPrimeGen1

      # Time the summing of primes.
      - name: RunTimerSumPrimes2
        run: |
          ./TimerPrimeGen2

      # Time the summing of primes.
      - name: RunTimerSumPrimes3
        run: |
          ./TimerPrimeGen3

      # Time the summing of primes.
      - name: RunTimerSumPrimes4
        run: |
          ./TimerPrimeGen4
