# This is a basic workflow to help you get started with Actions

name: TimeIt

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  MY_DEPENDENCY_FLAGS: "-Lprimesieve -Wl,-rpath=primesieve -Iprimesieve/include -Lmpfr/src/.libs -Wl,-rpath=mpfr/src/.libs -Impfr/src -Lgmp-6.3.0/.libs  -Wl,-rpath=gmp-6.3.0/.libs"
  IN_FILE: "checkpoints/Checkpoint_42hrs_20231211.txt"
  RUNTIME_MIN: 30
  OMP_DISPLAY_ENV: TRUE

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      # Set up environment
      - name: Setup
        run: |
          git rev-parse --short HEAD
          . ./scripts/Setup.sh

      # Run code straight, no profiling.
      - name: Run
        run: |
          JOB_STOP_TIME=`date --date="+$RUNTIME_MIN mins" +%s`
          OMP_PROC_BIND=TRUE OMP_PLACES="{0,1},{2,3}" /usr/bin/time -v ./Search 60 $JOB_STOP_TIME $IN_FILE

     # Compile code from main branch
      - name: Compile main
        run: |
          rm -rf Search code.profdata default.profraw primesieve mpfr gmp-6.3.0
          git checkout main
          git rev-parse --short HEAD
          . ./scripts/Setup.sh

      # Run main code straight, no profiling.
      - name: Run main
        run: |
          JOB_STOP_TIME=`date --date="+$RUNTIME_MIN mins" +%s`
          /usr/bin/time -v ./Search 60 $JOB_STOP_TIME $IN_FILE
