# This is a basic workflow to help you get started with Actions

name: TimeIt

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  MY_DEPENDENCY_FLAGS: "-Lprimesieve -Wl,-rpath=primesieve -Iprimesieve/include -Lmpfr/src/.libs -Wl,-rpath=mpfr/src/.libs -Impfr/src -Lgmp-6.2.1/.libs  -Wl,-rpath=gmp-6.2.1/.libs"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      # Set up environment
      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install libmpfr-dev gnuplot clang-12

      # build libprimesieve
      - name: SetupPrimeSieve
        run: bash scripts/SetupPrimeSieve.sh

      # Build GMP
      - name: SetupGMP
        run: bash scripts/SetupGMP.sh

      # Build MPFR
      - name: SetupMPFR
        run: bash scripts/SetupMPFR.sh

      # Compile code
      - name: Compile
        run: |
          git rev-parse --short HEAD
          clang++-12 -std=c++20 -DNDEBUG -fuse-ld=gold -Wall -O3 -flto=thin -march=native -Wl,-plugin-opt=whole-program-visibility -Lprimesieve -Wl,-rpath=primesieve -Iprimesieve/include Search.cpp -lmpfr -lprimesieve -o Search

      # Run code straight, no profiling.
      - name: Run
        run: ./Search 43

     # Compile code from main branch
      - name: Compile main
        run: |
          rm Search
          git checkout main
          git rev-parse --short HEAD
          clang++-12 -std=c++20 -DNDEBUG -fuse-ld=gold -Wall -O3 -flto=thin -march=native -Wl,-plugin-opt=whole-program-visibility -Lprimesieve -Wl,-rpath=primesieve -Iprimesieve/include Search.cpp -lmpfr -lprimesieve -o Search

      # Run main code straight, no profiling.
      - name: Run main
        run: ./Search 43
